name: Feature Request
description: Thanks for taking the time to fill out this feature request!
labels: [enhancement]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the problem
      description: What problem is your feature request targeting and why is it a problem? Please describe.
      placeholder: |
        A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe your solution
      description: Describe the solution you'd like
      placeholder: |
        A clear and concise description of what you want to happen.

  - type: textarea
    id: other
    attributes:
      label: Additional context
      placeholder: Add any other context about the feature request here.
